### ISSUE TITLE
How to disable authorization?

### ISSUE THREAD

**Issue by 4nte** [VolantMQ/volantmq#176]
Since `auth.anonymous` config option has been removed, is there another way of disabling authorization?

**Comment by troian** [comment]
yeah, i think it was hastily. i'll make it to work

**Comment by troian** [comment]
oh, i forgot (and need to update the documentation).
you can add this kind of user to `simplyAuth` config entry
```yaml
      - name: internal
        backend: simpleAuth
        config:
          users:
            "": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" # this hash is effectively sha256 of empty string
```
